name: Run lint checks

on:
  push:
    paths:
      - 'keymap_drawer/**'
      - pyproject.toml
      - uv.lock
  pull_request:
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Black
        run: uv run black --check keymap_drawer

      - name: Pylint
        run: uv run pylint --disable=fixme keymap_drawer
        if: success() || failure()

      - name: Mypy
        run: uv run mypy keymap_drawer
        if: success() || failure()

      - name: Deptry
        run: uv run deptry .
        if: success() || failure()
